version: "3.8"

services:
  app:
    image: minseokoh/blog-server
    container_name: app
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: blog
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: